name: Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependency Cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" 

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests.py

  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-Formatter
        uses: mezgoodle/auto-formatter@v1.0.10
            
      - uses: actions/checkout@v4

      - name: Setup Dependency Cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" 

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Flake
        run: flake8
